import bcrypt from "bcryptjs";

export const initialAirports = [
  // --- INDIA MAJOR HUBS & AIRPORTS ---
  {
    code: "DEL",
    name: "Indira Gandhi International Airport",
    city: "New Delhi",
    country: "India",
    lat: 28.5562,
    lng: 77.1000,
    terminals: 3,
    imageUrl: "https://images.unsplash.com/photo-1541410965313-d53b3c16ef17?auto=format&fit=crop&w=1200&q=80",
    description: "India's largest and busiest international aviation hub, featuring the iconic Terminal 3 and bronze Hastamudra sculptures.",
    region: "North India",
    elevation: 777,
    runways: 4,
  },
  {
    code: "BOM",
    name: "Chhatrapati Shivaji Maharaj International Airport",
    city: "Mumbai",
    country: "India",
    lat: 19.0896,
    lng: 72.8656,
    terminals: 2,
    imageUrl: "https://images.unsplash.com/photo-1570710891163-6d3b5c47248b?auto=format&fit=crop&w=1200&q=80",
    description: "World-class architectural marvel featuring the iconic peacock-motif coffered ceiling and the 3km Jaya He art walk.",
    region: "West India",
    elevation: 39,
    runways: 2,
  },
  {
    code: "BLR",
    name: "Kempegowda International Airport",
    city: "Bengaluru",
    country: "India",
    lat: 13.1986,
    lng: 77.7066,
    terminals: 2,
    imageUrl: "https://images.unsplash.com/photo-1569154941061-e231b4725ef1?auto=format&fit=crop&w=1200&q=80",
    description: "Award-winning UNESCO Prix Versailles winner known for Terminal 2 'Terminal in a Garden' with lush indoor flora and waterfalls.",
    region: "South India",
    elevation: 3000,
    runways: 2,
  },
  {
    code: "HYD",
    name: "Rajiv Gandhi International Airport",
    city: "Hyderabad",
    country: "India",
    lat: 17.2403,
    lng: 78.4294,
    terminals: 2,
    imageUrl: "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&w=1200&q=80",
    description: "Consistently ranked among the top airports globally for service quality, featuring an integrated passenger terminal and cargo village.",
    region: "South India",
    elevation: 2024,
    runways: 2,
  },
  {
    code: "MAA",
    name: "Chennai International Airport",
    city: "Chennai",
    country: "India",
    lat: 12.9941,
    lng: 80.1709,
    terminals: 2,
    imageUrl: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=1200&q=80",
    description: "Major aviation gateway to South India featuring the modern Golden Palm steel-and-glass terminal concourse.",
    region: "South India",
    elevation: 52,
    runways: 2,
  },
  {
    code: "CCU",
    name: "Netaji Subhash Chandra Bose International Airport",
    city: "Kolkata",
    country: "India",
    lat: 22.6547,
    lng: 88.4467,
    terminals: 2,
    imageUrl: "https://images.unsplash.com/photo-1508873696983-2df5293cb32f?auto=format&fit=crop&w=1200&q=80",
    description: "The premier international hub for Eastern and North-Eastern India, showcasing Bengali poetry ceiling calligraphy and copper roofs.",
    region: "East India",
    elevation: 16,
    runways: 2,
  },
  {
    code: "COK",
    name: "Cochin International Airport",
    city: "Kochi",
    country: "India",
    lat: 10.1518,
    lng: 76.3929,
    terminals: 3,
    imageUrl: "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=1200&q=80",
    description: "The world's first fully solar-powered airport, renowned for its traditional Kerala Nalukettu architectural roof design.",
    region: "South India",
    elevation: 30,
    runways: 1,
  },
  {
    code: "GOI",
    name: "Dabolim International Airport",
    city: "Goa",
    country: "India",
    lat: 15.3808,
    lng: 73.8314,
    terminals: 1,
    imageUrl: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=1200&q=80",
    description: "Historic coastal Goa international gateway overlooking the Arabian Sea, serving millions of beach and resort travelers.",
    region: "West India",
    elevation: 184,
    runways: 1,
  },
  {
    code: "GOX",
    name: "Manohar International Airport",
    city: "Mopa (Goa)",
    country: "India",
    lat: 15.7483,
    lng: 73.8647,
    terminals: 1,
    imageUrl: "https://images.unsplash.com/photo-1464037866556-6812c9d1c72e?auto=format&fit=crop&w=1200&q=80",
    description: "Ultra-modern greenfield airport in North Goa designed with Portuguese azulejo art motifs and sustainable solar architecture.",
    region: "West India",
    elevation: 560,
    runways: 1,
  },
  {
    code: "AMD",
    name: "Sardar Vallabhbhai Patel International Airport",
    city: "Ahmedabad",
    country: "India",
    lat: 23.0772,
    lng: 72.6347,
    terminals: 2,
    imageUrl: "https://images.unsplash.com/photo-1587019158091-1a103c5dd17f?auto=format&fit=crop&w=1200&q=80",
    description: "Gujarat's busiest aviation gateway featuring contemporary tensile steel canopies and vibrant regional handicraft displays.",
    region: "West India",
    elevation: 189,
    runways: 1,
  },
  {
    code: "PNQ",
    name: "Pune International Airport",
    city: "Pune",
    country: "India",
    lat: 18.5822,
    lng: 73.9197,
    terminals: 2,
    imageUrl: "https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&w=1200&q=80",
    description: "Maharashtra's IT & manufacturing hub airport featuring a grand new integrated terminal with Maratha fortress-inspired facade.",
    region: "West India",
    elevation: 1942,
    runways: 1,
  },
  {
    code: "JAI",
    name: "Jaipur International Airport",
    city: "Jaipur",
    country: "India",
    lat: 26.8242,
    lng: 75.8122,
    terminals: 2,
    imageUrl: "https://images.unsplash.com/photo-1609766857041-ed402ea8069a?auto=format&fit=crop&w=1200&q=80",
    description: "The iconic Pink City gateway with grand red sandstone Jali screens, Rajasthani royal archways, and heritage domes.",
    region: "North India",
    elevation: 1263,
    runways: 1,
  },
  {
    code: "VNS",
    name: "Lal Bahadur Shastri International Airport",
    city: "Varanasi",
    country: "India",
    lat: 25.4524,
    lng: 82.8593,
    terminals: 1,
    imageUrl: "https://images.unsplash.com/photo-1561361513-2d000a50f0dc?auto=format&fit=crop&w=1200&q=80",
    description: "Gateway to the world's oldest living city, featuring illuminated brass sculptures, mural ghats, and spiritual heritage decor.",
    region: "North India",
    elevation: 266,
    runways: 1,
  },
  {
    code: "IXC",
    name: "Shaheed Bhagat Singh International Airport",
    city: "Chandigarh",
    country: "India",
    lat: 30.6735,
    lng: 76.7885,
    terminals: 1,
    imageUrl: "https://images.unsplash.com/photo-1520437358207-323b43b50729?auto=format&fit=crop&w=1200&q=80",
    description: "Modernist glass-and-steel green terminal building blending Le Corbusier geometry with expansive indoor botanical plantings.",
    region: "North India",
    elevation: 1012,
    runways: 1,
  },
  {
    code: "TRV",
    name: "Thiruvananthapuram International Airport",
    city: "Thiruvananthapuram",
    country: "India",
    lat: 8.4821,
    lng: 76.9200,
    terminals: 2,
    imageUrl: "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?auto=format&fit=crop&w=1200&q=80",
    description: "Kerala's first airport, situated just 1km from Shankumugham beach with sweeping views of the Arabian Sea.",
    region: "South India",
    elevation: 15,
    runways: 1,
  },
  {
    code: "ATQ",
    name: "Sri Guru Ram Dass Jee International Airport",
    city: "Amritsar",
    country: "India",
    lat: 31.7096,
    lng: 74.7973,
    terminals: 1,
    imageUrl: "https://images.unsplash.com/photo-1594913785162-e678a0c23ecb?auto=format&fit=crop&w=1200&q=80",
    description: "The primary international gateway to Punjab and the Golden Temple, handling high volumes of diaspora and pilgrimage travel.",
    region: "North India",
    elevation: 756,
    runways: 1,
  },
  {
    code: "SXR",
    name: "Sheikh ul-Alam International Airport",
    city: "Srinagar (Kashmir)",
    country: "India",
    lat: 33.9871,
    lng: 74.7744,
    terminals: 1,
    imageUrl: "https://images.unsplash.com/photo-1598091383021-15ddea10925d?auto=format&fit=crop&w=1200&q=80",
    description: "Spectacular alpine airport nestled in the Kashmir Valley surrounded by snow-capped Pir Panjal and Himalayan ranges.",
    region: "North India",
    elevation: 5429,
    runways: 1,
  },
  {
    code: "GAU",
    name: "Lokpriya Gopinath Bordoloi International Airport",
    city: "Guwahati",
    country: "India",
    lat: 26.1061,
    lng: 91.5859,
    terminals: 2,
    imageUrl: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80",
    description: "The premier aviation hub connecting the 'Seven Sister' states of Northeast India along the mighty Brahmaputra River.",
    region: "Northeast India",
    elevation: 162,
    runways: 1,
  },
  {
    code: "IXB",
    name: "Bagdogra International Airport",
    city: "Siliguri / Darjeeling",
    country: "India",
    lat: 26.6812,
    lng: 88.3286,
    terminals: 1,
    imageUrl: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1200&q=80",
    description: "Scenic Himalayan foothills gateway serving Darjeeling tea estates, Sikkim, Bhutan, and the Kanchenjunga mountain circuits.",
    region: "East India",
    elevation: 412,
    runways: 1,
  },
  {
    code: "IXZ",
    name: "Veer Savarkar International Airport",
    city: "Port Blair",
    country: "India",
    lat: 11.6410,
    lng: 92.7297,
    terminals: 1,
    imageUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80",
    description: "Iconic seashell-shaped ocean terminal with 100% natural skylight illumination, serving the tropical Andaman archipelago.",
    region: "Island Territories",
    elevation: 52,
    runways: 1,
  },
  {
    code: "BBI",
    name: "Biju Patnaik International Airport",
    city: "Bhubaneswar",
    country: "India",
    lat: 20.2444,
    lng: 85.8178,
    terminals: 2,
    imageUrl: "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=1200&q=80",
    description: "Odisha's premier international airport adorned with hand-carved Kalinga stone temple sculptures, Konark wheels, and Pattachitra art.",
    region: "East India",
    elevation: 138,
    runways: 1,
  },
  {
    code: "PAT",
    name: "Jay Prakash Narayan Airport",
    city: "Patna",
    country: "India",
    lat: 25.5913,
    lng: 85.0880,
    terminals: 1,
    imageUrl: "https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=1200&q=80",
    description: "Ancient historical capital gateway along the Ganges in Bihar, handling extensive commercial transit across Eastern India.",
    region: "East India",
    elevation: 170,
    runways: 1,
  },
  {
    code: "IXE",
    name: "Mangaluru International Airport",
    city: "Mangalore",
    country: "India",
    lat: 12.9613,
    lng: 74.8900,
    terminals: 1,
    imageUrl: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80",
    description: "Renowned hilltop tabletop airport situated on the cliffs of Bajpe overlooking the lush Western Ghats and Arabian Sea.",
    region: "South India",
    elevation: 336,
    runways: 1,
  },
  {
    code: "VTZ",
    name: "Visakhapatnam International Airport",
    city: "Visakhapatnam",
    country: "India",
    lat: 17.7212,
    lng: 83.2245,
    terminals: 1,
    imageUrl: "https://images.unsplash.com/photo-1509233725247-49e657c54213?auto=format&fit=crop&w=1200&q=80",
    description: "Andhra Pradesh's largest commercial port city airport operating 24/7 with dual civilian-naval state-of-the-art runway systems.",
    region: "South India",
    elevation: 17,
    runways: 1,
  },
  {
    code: "LKO",
    name: "Chaudhary Charan Singh International Airport",
    city: "Lucknow",
    country: "India",
    lat: 26.7606,
    lng: 80.8893,
    terminals: 3,
    imageUrl: "https://images.unsplash.com/photo-1562979314-bee7453e911c?auto=format&fit=crop&w=1200&q=80",
    description: "Brand-new Terminal 3 masterpiece combining Awadhi architectural elegance, Chikankari artwork, and automated biometric boarding.",
    region: "North India",
    elevation: 405,
    runways: 1,
  },
  {
    code: "NAG",
    name: "Dr. Babasaheb Ambedkar International Airport",
    city: "Nagpur",
    country: "India",
    lat: 21.0922,
    lng: 79.0472,
    terminals: 1,
    imageUrl: "https://images.unsplash.com/photo-1521791136064-7986c2920216?auto=format&fit=crop&w=1200&q=80",
    description: "Located at the geographic Zero Milestone of India, serving as the multi-modal cargo and commercial hub for Central India.",
    region: "Central India",
    elevation: 1033,
    runways: 1,
  },
  {
    code: "UDR",
    name: "Maharana Pratap Airport",
    city: "Udaipur",
    country: "India",
    lat: 24.6177,
    lng: 73.8961,
    terminals: 1,
    imageUrl: "https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=1200&q=80",
    description: "Royal city of lakes gateway with Rajasthani white marble decor and majestic views of the surrounding Aravalli mountain ranges.",
    region: "North India",
    elevation: 1684,
    runways: 1,
  },
  {
    code: "IDR",
    name: "Devi Ahilya Bai Holkar Airport",
    city: "Indore",
    country: "India",
    lat: 22.7217,
    lng: 75.8011,
    terminals: 1,
    imageUrl: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=1200&q=80",
    description: "Central India's busiest airport in India's cleanest city, equipped with state-of-the-art night landing and passenger concourses.",
    region: "Central India",
    elevation: 1849,
    runways: 1,
  },
  {
    code: "IXJ",
    name: "Jammu Airport",
    city: "Jammu",
    country: "India",
    lat: 32.6891,
    lng: 74.8374,
    terminals: 1,
    imageUrl: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80",
    description: "The winter capital gateway to Jammu & Kashmir serving millions of Vaishno Devi pilgrims and Himalayan travelers.",
    region: "North India",
    elevation: 1029,
    runways: 1,
  },
  {
    code: "IXR",
    name: "Birsa Munda Airport",
    city: "Ranchi",
    country: "India",
    lat: 23.3143,
    lng: 85.3217,
    terminals: 1,
    imageUrl: "https://images.unsplash.com/photo-1518684079-3c830dcef090?auto=format&fit=crop&w=1200&q=80",
    description: "Jharkhand's premier airport recognized as one of India's top customer satisfaction airports with eco-friendly solar systems.",
    region: "East India",
    elevation: 2148,
    runways: 1,
  },
  {
    code: "CJB",
    name: "Coimbatore International Airport",
    city: "Coimbatore",
    country: "India",
    lat: 11.0298,
    lng: 77.0434,
    terminals: 1,
    imageUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80",
    description: "The textile and industrial capital of Tamil Nadu, situated at the gateway to the Nilgiri hills and Ooty.",
    region: "South India",
    elevation: 1319,
    runways: 1,
  },
  {
    code: "IXM",
    name: "Madurai Airport",
    city: "Madurai",
    country: "India",
    lat: 9.8345,
    lng: 78.0934,
    terminals: 1,
    imageUrl: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=1200&q=80",
    description: "Cultural capital of Tamil Nadu gateway featuring Dravidian temple tower stone architecture and silk weaving art motifs.",
    region: "South India",
    elevation: 446,
    runways: 1,
  },
  {
    code: "VGA",
    name: "Vijayawada International Airport",
    city: "Vijayawada",
    country: "India",
    lat: 16.5304,
    lng: 80.7968,
    terminals: 1,
    imageUrl: "https://images.unsplash.com/photo-1477959858617-67f30bc54b38?auto=format&fit=crop&w=1200&q=80",
    description: "Modern glass-canopy airport serving the Andhra Pradesh Amaravati capital region and Krishna river valley.",
    region: "South India",
    elevation: 82,
    runways: 1,
  },
  {
    code: "TIR",
    name: "Tirupati Airport",
    city: "Tirupati",
    country: "India",
    lat: 13.6325,
    lng: 79.5433,
    terminals: 1,
    imageUrl: "https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=1200&q=80",
    description: "Architectural marvel shaped like the divine mythical bird Garuda, welcoming millions of pilgrims to the holy Tirumala hills.",
    region: "South India",
    elevation: 350,
    runways: 1,
  },
  {
    code: "DED",
    name: "Jolly Grant Airport",
    city: "Dehradun",
    country: "India",
    lat: 30.1897,
    lng: 78.1803,
    terminals: 1,
    imageUrl: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80",
    description: "Scenic Himalayan gateway terminal nestled between Dehradun, Rishikesh, and Haridwar with glass views of mountain forests.",
    region: "North India",
    elevation: 1831,
    runways: 1,
  },

  // --- WORLD PREMIER HUB AIRPORTS ---
  {
    code: "DXB",
    name: "Dubai International Airport",
    city: "Dubai",
    country: "United Arab Emirates",
    lat: 25.2532,
    lng: 55.3657,
    terminals: 3,
    imageUrl: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=1200&q=80",
    description: "World's busiest international airport by passenger traffic, featuring arching glass concourses and Emirates super-hub operations.",
    region: "Middle East",
    elevation: 62,
    runways: 2,
  },
  {
    code: "SIN",
    name: "Singapore Changi Airport",
    city: "Singapore",
    country: "Singapore",
    lat: 1.3644,
    lng: 103.9915,
    terminals: 4,
    imageUrl: "https://images.unsplash.com/photo-1525625293386-3f8f99389edd?auto=format&fit=crop&w=1200&q=80",
    description: "Consistently voted World's Best Airport, famous for the Jewel dome, 40m indoor HSBC Rain Vortex waterfall, and tropical butterfly garden.",
    region: "Asia Pacific",
    elevation: 22,
    runways: 3,
  },
  {
    code: "LHR",
    name: "London Heathrow Airport",
    city: "London",
    country: "United Kingdom",
    lat: 51.4700,
    lng: -0.4543,
    terminals: 5,
    imageUrl: "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=1200&q=80",
    description: "Europe's foremost transatlantic aviation hub featuring the iconic Terminal 5 wave roof and British Airways global network.",
    region: "Europe",
    elevation: 83,
    runways: 2,
  },
  {
    code: "JFK",
    name: "John F. Kennedy International Airport",
    city: "New York",
    country: "United States",
    lat: 40.6413,
    lng: -73.7781,
    terminals: 6,
    imageUrl: "https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?auto=format&fit=crop&w=1200&q=80",
    description: "New York's premier international gateway featuring the legendary Eero Saarinen TWA Flight Center and transatlantic corridors.",
    region: "North America",
    elevation: 13,
    runways: 4,
  },
  {
    code: "HND",
    name: "Tokyo Haneda Airport",
    city: "Tokyo",
    country: "Japan",
    lat: 35.5494,
    lng: 139.7798,
    terminals: 3,
    imageUrl: "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=1200&q=80",
    description: "World's cleanest and most punctual mega-hub, featuring the Edo Koji traditional street market and Mt. Fuji runway views.",
    region: "Asia Pacific",
    elevation: 21,
    runways: 4,
  },
  {
    code: "CDG",
    name: "Paris Charles de Gaulle Airport",
    city: "Paris",
    country: "France",
    lat: 49.0097,
    lng: 2.5479,
    terminals: 3,
    imageUrl: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=1200&q=80",
    description: "France's principal airport renowned for Paul Andreu's futuristic glass tube walkways inside circular Terminal 1.",
    region: "Europe",
    elevation: 392,
    runways: 4,
  },
  {
    code: "FRA",
    name: "Frankfurt Airport",
    city: "Frankfurt",
    country: "Germany",
    lat: 50.0379,
    lng: 8.5622,
    terminals: 2,
    imageUrl: "https://images.unsplash.com/photo-1467269204594-9661b134dd2b?auto=format&fit=crop&w=1200&q=80",
    description: "Germany's largest aviation superhub, featuring the integrated futuristic AirRail glass center and Lufthansa World Headquarters.",
    region: "Europe",
    elevation: 364,
    runways: 4,
  },
  {
    code: "AMS",
    name: "Amsterdam Airport Schiphol",
    city: "Amsterdam",
    country: "Netherlands",
    lat: 52.3105,
    lng: 4.7683,
    terminals: 1,
    imageUrl: "https://images.unsplash.com/photo-1534351590666-13e3e96b5017?auto=format&fit=crop&w=1200&q=80",
    description: "One of the world's oldest continuous airports, built below sea level with a single-terminal concourse and famous Schiphol Plaza.",
    region: "Europe",
    elevation: -11,
    runways: 6,
  },
  {
    code: "SYD",
    name: "Sydney Kingsford Smith Airport",
    city: "Sydney",
    country: "Australia",
    lat: -33.9399,
    lng: 151.1753,
    terminals: 3,
    imageUrl: "https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?auto=format&fit=crop&w=1200&q=80",
    description: "Australia's primary international gateway, where runways project directly into Botany Bay with views of the Sydney skyline.",
    region: "Oceania",
    elevation: 21,
    runways: 3,
  },
  {
    code: "DOH",
    name: "Hamad International Airport",
    city: "Doha",
    country: "Qatar",
    lat: 25.2609,
    lng: 51.6138,
    terminals: 1,
    imageUrl: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=1200&q=80",
    description: "Skytrax World's Best Airport winner featuring the iconic 23-foot bronze Lamp Bear and 'The Orchard' 6,000 sqm indoor tropical garden.",
    region: "Middle East",
    elevation: 13,
    runways: 2,
  },
  {
    code: "ICN",
    name: "Incheon International Airport",
    city: "Seoul",
    country: "South Korea",
    lat: 37.4602,
    lng: 126.4407,
    terminals: 2,
    imageUrl: "https://images.unsplash.com/photo-1538485399081-7191377e8241?auto=format&fit=crop&w=1200&q=80",
    description: "Korea's ultra-efficient aviation hub featuring traditional Korean pine garden pavilions, ice skating rink, and autonomous service robots.",
    region: "Asia Pacific",
    elevation: 23,
    runways: 4,
  },
  {
    code: "BKK",
    name: "Suvarnabhumi Airport",
    city: "Bangkok",
    country: "Thailand",
    lat: 13.6900,
    lng: 100.7501,
    terminals: 1,
    imageUrl: "https://images.unsplash.com/photo-1508009603885-50cf7c579365?auto=format&fit=crop&w=1200&q=80",
    description: "Thailand's 'Golden Land' mega-terminal featuring towering 5-meter Yaksha demon statues and sweeping steel-and-fabric concourses.",
    region: "Asia Pacific",
    elevation: 5,
    runways: 3,
  },
  {
    code: "IST",
    name: "Istanbul Airport",
    city: "Istanbul",
    country: "Turkey",
    lat: 41.2753,
    lng: 28.7519,
    terminals: 1,
    imageUrl: "https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?auto=format&fit=crop&w=1200&q=80",
    description: "World's largest single-roof terminal under one roof, with a distinctive tulip-inspired Air Traffic Control tower bridging East and West.",
    region: "Europe / Middle East",
    elevation: 325,
    runways: 5,
  },
  {
    code: "LAX",
    name: "Los Angeles International Airport",
    city: "Los Angeles",
    country: "United States",
    lat: 33.9416,
    lng: -118.4085,
    terminals: 9,
    imageUrl: "https://images.unsplash.com/photo-1580655653885-65763b2597d0?auto=format&fit=crop&w=1200&q=80",
    description: "The premier gateway to the Pacific Rim, featuring the mid-century Space Age Theme Building and Tom Bradley International Terminal.",
    region: "North America",
    elevation: 128,
    runways: 4,
  },
  {
    code: "SFO",
    name: "San Francisco International Airport",
    city: "San Francisco",
    country: "United States",
    lat: 37.6213,
    lng: -122.3790,
    terminals: 4,
    imageUrl: "https://images.unsplash.com/photo-1501594907352-04cda38ebc29?auto=format&fit=crop&w=1200&q=80",
    description: "Renowned for its soaring wing-like International Terminal, SFO Museum art exhibits, and eco-friendly LEED Platinum facilities.",
    region: "North America",
    elevation: 13,
    runways: 4,
  },
  {
    code: "ORD",
    name: "Chicago O'Hare International Airport",
    city: "Chicago",
    country: "United States",
    lat: 41.9742,
    lng: -87.9073,
    terminals: 4,
    imageUrl: "https://images.unsplash.com/photo-1477959858617-67f30bc54b38?auto=format&fit=crop&w=1200&q=80",
    description: "One of the world's most connected airports, famous for the kinetic neon sculpture 'The Sky's the Limit' tunnel in Concourse B/C.",
    region: "North America",
    elevation: 668,
    runways: 8,
  },
  {
    code: "YYZ",
    name: "Toronto Pearson International Airport",
    city: "Toronto",
    country: "Canada",
    lat: 43.6777,
    lng: -79.6248,
    terminals: 2,
    imageUrl: "https://images.unsplash.com/photo-1517090504586-fde19ea6066f?auto=format&fit=crop&w=1200&q=80",
    description: "Canada's largest and busiest international gateway, handling over 50 million travelers with modern high-speed automated transit.",
    region: "North America",
    elevation: 569,
    runways: 5,
  },
  {
    code: "ZRH",
    name: "Zurich Airport",
    city: "Zurich",
    country: "Switzerland",
    lat: 47.4582,
    lng: 8.5555,
    terminals: 3,
    imageUrl: "https://images.unsplash.com/photo-1515488764276-beab7607c1e6?auto=format&fit=crop&w=1200&q=80",
    description: "Swiss precision engineering at its finest, offering panoramic Alpine observation decks, timber architecture, and subterranean Skymetro.",
    region: "Europe",
    elevation: 1416,
    runways: 3,
  },
  {
    code: "MAD",
    name: "Adolfo Suárez Madrid–Barajas Airport",
    city: "Madrid",
    country: "Spain",
    lat: 40.4839,
    lng: -3.5680,
    terminals: 4,
    imageUrl: "https://images.unsplash.com/photo-1539037116277-4db20889f2d4?auto=format&fit=crop&w=1200&q=80",
    description: "Architectural masterpiece designed by Richard Rogers featuring undulating rainbow-hued bamboo ceiling waves in Terminal 4.",
    region: "Europe",
    elevation: 1998,
    runways: 4,
  },
  {
    code: "FCO",
    name: "Leonardo da Vinci–Fiumicino Airport",
    city: "Rome",
    country: "Italy",
    lat: 41.8003,
    lng: 12.2389,
    terminals: 3,
    imageUrl: "https://images.unsplash.com/photo-1552832230-c0197dd311b5?auto=format&fit=crop&w=1200&q=80",
    description: "Italy's primary international hub adorned with classical Roman marble columns, luxury Italian fashion plazas, and Mediterranean cuisine.",
    region: "Europe",
    elevation: 14,
    runways: 3,
  },
  {
    code: "MEL",
    name: "Melbourne Airport",
    city: "Melbourne",
    country: "Australia",
    lat: -37.6690,
    lng: 144.8410,
    terminals: 4,
    imageUrl: "https://images.unsplash.com/photo-1514395462725-fb4566210144?auto=format&fit=crop&w=1200&q=80",
    description: "Australia's second-busiest aviation hub operating 24 hours a day with aerodynamic curved passenger concourses.",
    region: "Oceania",
    elevation: 434,
    runways: 2,
  },
  {
    code: "CPT",
    name: "Cape Town International Airport",
    city: "Cape Town",
    country: "South Africa",
    lat: -33.9715,
    lng: 18.6021,
    terminals: 2,
    imageUrl: "https://images.unsplash.com/photo-1580618672591-eb180b1a973f?auto=format&fit=crop&w=1200&q=80",
    description: "Africa's most scenic international gateway offering spectacular direct views of Table Mountain directly from boarding gates.",
    region: "Africa",
    elevation: 151,
    runways: 2,
  },
  {
    code: "GRU",
    name: "São Paulo/Guarulhos International Airport",
    city: "São Paulo",
    country: "Brazil",
    lat: -23.4356,
    lng: -46.4731,
    terminals: 3,
    imageUrl: "https://images.unsplash.com/photo-1516306580123-e6e52b1b7b5f?auto=format&fit=crop&w=1200&q=80",
    description: "The premier international hub for South America, connecting Brazil's economic heart to Latin America, North America, and Europe.",
    region: "South America",
    elevation: 2460,
    runways: 2,
  },
  {
    code: "NRT",
    name: "Narita International Airport",
    city: "Tokyo",
    country: "Japan",
    lat: 35.7720,
    lng: 140.3929,
    terminals: 3,
    imageUrl: "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=1200&q=80",
    description: "Japan's primary transpacific hub, featuring serene Japanese tea gardens, Kabuki cultural showcases, and high-speed Skyliner links.",
    region: "Asia Pacific",
    elevation: 141,
    runways: 2,
  },
  {
    code: "KUL",
    name: "Kuala Lumpur International Airport",
    city: "Kuala Lumpur",
    country: "Malaysia",
    lat: 2.7456,
    lng: 101.7099,
    terminals: 2,
    imageUrl: "https://images.unsplash.com/photo-1596422846543-75c6fc197f07?auto=format&fit=crop&w=1200&q=80",
    description: "Masterpiece by Kisho Kurokawa designed around the concept 'Airport in the Forest, Forest in the Airport' with tropical rainforests.",
    region: "Asia Pacific",
    elevation: 69,
    runways: 3,
  },
];

export const initialRoutes = [
  // India Metros & Core Hub Connections
  { source: "HYD", destination: "DEL", distanceKm: 1250, baseCost: 110, durationMinutes: 135, airlines: ["AirServe", "Air India", "IndiGo"] },
  { source: "HYD", destination: "BOM", distanceKm: 620, baseCost: 75, durationMinutes: 85, airlines: ["AirServe", "IndiGo"] },
  { source: "HYD", destination: "BLR", distanceKm: 500, baseCost: 60, durationMinutes: 70, airlines: ["AirServe", "IndiGo"] },
  { source: "HYD", destination: "MAA", distanceKm: 520, baseCost: 65, durationMinutes: 75, airlines: ["AirServe"] },
  { source: "HYD", destination: "CCU", distanceKm: 1180, baseCost: 105, durationMinutes: 130, airlines: ["AirServe", "IndiGo"] },
  { source: "HYD", destination: "COK", distanceKm: 860, baseCost: 85, durationMinutes: 105, airlines: ["AirServe", "IndiGo"] },
  { source: "HYD", destination: "GOI", distanceKm: 540, baseCost: 70, durationMinutes: 80, airlines: ["AirServe", "IndiGo"] },
  { source: "HYD", destination: "GOX", distanceKm: 530, baseCost: 72, durationMinutes: 75, airlines: ["AirServe"] },
  { source: "HYD", destination: "VTZ", distanceKm: 500, baseCost: 55, durationMinutes: 65, airlines: ["AirServe", "IndiGo"] },
  { source: "HYD", destination: "VGA", distanceKm: 275, baseCost: 40, durationMinutes: 45, airlines: ["AirServe"] },
  { source: "HYD", destination: "TIR", distanceKm: 430, baseCost: 50, durationMinutes: 60, airlines: ["AirServe"] },
  { source: "HYD", destination: "PNQ", distanceKm: 500, baseCost: 65, durationMinutes: 70, airlines: ["AirServe", "IndiGo"] },
  { source: "HYD", destination: "AMD", distanceKm: 880, baseCost: 90, durationMinutes: 105, airlines: ["AirServe", "IndiGo"] },
  { source: "HYD", destination: "JAI", distanceKm: 1090, baseCost: 100, durationMinutes: 120, airlines: ["AirServe"] },
  { source: "HYD", destination: "VNS", distanceKm: 990, baseCost: 95, durationMinutes: 115, airlines: ["AirServe", "IndiGo"] },
  { source: "HYD", destination: "DXB", distanceKm: 2550, baseCost: 240, durationMinutes: 240, airlines: ["AirServe", "Emirates"] },
  { source: "HYD", destination: "SIN", distanceKm: 3300, baseCost: 290, durationMinutes: 285, airlines: ["AirServe", "Singapore Airlines"] },
  { source: "HYD", destination: "DOH", distanceKm: 2780, baseCost: 260, durationMinutes: 260, airlines: ["AirServe", "Qatar Airways"] },
  { source: "HYD", destination: "KUL", distanceKm: 3120, baseCost: 270, durationMinutes: 270, airlines: ["AirServe", "Malaysia Airlines"] },

  { source: "DEL", destination: "BOM", distanceKm: 1150, baseCost: 105, durationMinutes: 130, airlines: ["AirServe", "Air India", "IndiGo"] },
  { source: "DEL", destination: "BLR", distanceKm: 1740, baseCost: 130, durationMinutes: 165, airlines: ["AirServe", "IndiGo"] },
  { source: "DEL", destination: "MAA", distanceKm: 1760, baseCost: 135, durationMinutes: 165, airlines: ["AirServe", "IndiGo"] },
  { source: "DEL", destination: "CCU", distanceKm: 1300, baseCost: 115, durationMinutes: 140, airlines: ["AirServe", "Air India"] },
  { source: "DEL", destination: "COK", distanceKm: 2050, baseCost: 150, durationMinutes: 195, airlines: ["AirServe", "Air India"] },
  { source: "DEL", destination: "GOI", distanceKm: 1510, baseCost: 120, durationMinutes: 150, airlines: ["AirServe", "IndiGo"] },
  { source: "DEL", destination: "GOX", distanceKm: 1500, baseCost: 125, durationMinutes: 145, airlines: ["AirServe"] },
  { source: "DEL", destination: "AMD", distanceKm: 760, baseCost: 75, durationMinutes: 90, airlines: ["AirServe", "IndiGo"] },
  { source: "DEL", destination: "PNQ", distanceKm: 1170, baseCost: 105, durationMinutes: 130, airlines: ["AirServe", "IndiGo"] },
  { source: "DEL", destination: "JAI", distanceKm: 235, baseCost: 35, durationMinutes: 50, airlines: ["AirServe", "IndiGo"] },
  { source: "DEL", destination: "VNS", distanceKm: 675, baseCost: 70, durationMinutes: 85, airlines: ["AirServe", "IndiGo"] },
  { source: "DEL", destination: "IXC", distanceKm: 235, baseCost: 40, durationMinutes: 50, airlines: ["AirServe"] },
  { source: "DEL", destination: "ATQ", distanceKm: 410, baseCost: 55, durationMinutes: 65, airlines: ["AirServe", "IndiGo"] },
  { source: "DEL", destination: "SXR", distanceKm: 645, baseCost: 85, durationMinutes: 85, airlines: ["AirServe", "Air India"] },
  { source: "DEL", destination: "GAU", distanceKm: 1460, baseCost: 125, durationMinutes: 145, airlines: ["AirServe", "IndiGo"] },
  { source: "DEL", destination: "IXB", distanceKm: 1120, baseCost: 110, durationMinutes: 125, airlines: ["AirServe", "SpiceJet"] },
  { source: "DEL", destination: "PAT", distanceKm: 850, baseCost: 85, durationMinutes: 100, airlines: ["AirServe", "IndiGo"] },
  { source: "DEL", destination: "LKO", distanceKm: 420, baseCost: 50, durationMinutes: 65, airlines: ["AirServe", "IndiGo"] },
  { source: "DEL", destination: "DED", distanceKm: 210, baseCost: 40, durationMinutes: 45, airlines: ["AirServe"] },
  { source: "DEL", destination: "IXJ", distanceKm: 500, baseCost: 65, durationMinutes: 75, airlines: ["AirServe"] },
  { source: "DEL", destination: "DXB", distanceKm: 2180, baseCost: 220, durationMinutes: 220, airlines: ["AirServe", "Emirates", "Air India"] },
  { source: "DEL", destination: "DOH", distanceKm: 2540, baseCost: 245, durationMinutes: 240, airlines: ["AirServe", "Qatar Airways"] },
  { source: "DEL", destination: "LHR", distanceKm: 6710, baseCost: 680, durationMinutes: 560, airlines: ["AirServe", "British Airways", "Air India"] },
  { source: "DEL", destination: "CDG", distanceKm: 6580, baseCost: 670, durationMinutes: 545, airlines: ["AirServe", "Air France"] },
  { source: "DEL", destination: "FRA", distanceKm: 6120, baseCost: 650, durationMinutes: 520, airlines: ["AirServe", "Lufthansa"] },
  { source: "DEL", destination: "AMS", distanceKm: 6360, baseCost: 660, durationMinutes: 535, airlines: ["AirServe", "KLM"] },
  { source: "DEL", destination: "IST", distanceKm: 4540, baseCost: 490, durationMinutes: 410, airlines: ["AirServe", "Turkish Airlines"] },
  { source: "DEL", destination: "JFK", distanceKm: 11750, baseCost: 980, durationMinutes: 920, airlines: ["AirServe", "Air India"] },
  { source: "DEL", destination: "ORD", distanceKm: 12050, baseCost: 1020, durationMinutes: 940, airlines: ["AirServe", "United Airlines"] },
  { source: "DEL", destination: "SFO", distanceKm: 12350, baseCost: 1080, durationMinutes: 960, airlines: ["AirServe", "Air India"] },
  { source: "DEL", destination: "SIN", distanceKm: 4150, baseCost: 310, durationMinutes: 330, airlines: ["AirServe", "Singapore Airlines"] },
  { source: "DEL", destination: "BKK", distanceKm: 2920, baseCost: 230, durationMinutes: 245, airlines: ["AirServe", "Thai Airways"] },
  { source: "DEL", destination: "HND", distanceKm: 5840, baseCost: 590, durationMinutes: 480, airlines: ["AirServe", "ANA", "Japan Airlines"] },
  { source: "DEL", destination: "ICN", distanceKm: 4680, baseCost: 520, durationMinutes: 410, airlines: ["AirServe", "Korean Air"] },

  { source: "BOM", destination: "BLR", distanceKm: 840, baseCost: 85, durationMinutes: 100, airlines: ["AirServe", "IndiGo"] },
  { source: "BOM", destination: "MAA", distanceKm: 1030, baseCost: 95, durationMinutes: 115, airlines: ["AirServe"] },
  { source: "BOM", destination: "CCU", distanceKm: 1660, baseCost: 130, durationMinutes: 160, airlines: ["AirServe", "IndiGo"] },
  { source: "BOM", destination: "COK", distanceKm: 1060, baseCost: 95, durationMinutes: 115, airlines: ["AirServe", "IndiGo"] },
  { source: "BOM", destination: "GOI", distanceKm: 430, baseCost: 55, durationMinutes: 65, airlines: ["AirServe", "IndiGo"] },
  { source: "BOM", destination: "GOX", distanceKm: 420, baseCost: 58, durationMinutes: 60, airlines: ["AirServe"] },
  { source: "BOM", destination: "AMD", distanceKm: 440, baseCost: 55, durationMinutes: 65, airlines: ["AirServe", "IndiGo"] },
  { source: "BOM", destination: "PNQ", distanceKm: 120, baseCost: 30, durationMinutes: 40, airlines: ["AirServe"] },
  { source: "BOM", destination: "JAI", distanceKm: 915, baseCost: 85, durationMinutes: 105, airlines: ["AirServe", "IndiGo"] },
  { source: "BOM", destination: "UDR", distanceKm: 620, baseCost: 70, durationMinutes: 80, airlines: ["AirServe"] },
  { source: "BOM", destination: "IDR", distanceKm: 510, baseCost: 65, durationMinutes: 75, airlines: ["AirServe"] },
  { source: "BOM", destination: "NAG", distanceKm: 690, baseCost: 75, durationMinutes: 90, airlines: ["AirServe"] },
  { source: "BOM", destination: "IXE", distanceKm: 710, baseCost: 75, durationMinutes: 85, airlines: ["AirServe"] },
  { source: "BOM", destination: "TRV", distanceKm: 1250, baseCost: 110, durationMinutes: 125, airlines: ["AirServe"] },
  { source: "BOM", destination: "DXB", distanceKm: 1930, baseCost: 195, durationMinutes: 190, airlines: ["AirServe", "Emirates"] },
  { source: "BOM", destination: "DOH", distanceKm: 2290, baseCost: 220, durationMinutes: 215, airlines: ["AirServe", "Qatar Airways"] },
  { source: "BOM", destination: "LHR", distanceKm: 7200, baseCost: 690, durationMinutes: 590, airlines: ["AirServe", "British Airways"] },
  { source: "BOM", destination: "CDG", distanceKm: 7010, baseCost: 680, durationMinutes: 575, airlines: ["AirServe", "Air France"] },
  { source: "BOM", destination: "FRA", distanceKm: 6560, baseCost: 660, durationMinutes: 545, airlines: ["AirServe", "Lufthansa"] },
  { source: "BOM", destination: "AMS", distanceKm: 6860, baseCost: 670, durationMinutes: 560, airlines: ["AirServe", "KLM"] },
  { source: "BOM", destination: "SIN", distanceKm: 3900, baseCost: 320, durationMinutes: 325, airlines: ["AirServe", "Singapore Airlines"] },
  { source: "BOM", destination: "BKK", distanceKm: 3000, baseCost: 240, durationMinutes: 260, airlines: ["AirServe", "Thai Airways"] },
  { source: "BOM", destination: "JFK", distanceKm: 12500, baseCost: 1050, durationMinutes: 980, airlines: ["AirServe", "Air India"] },
  { source: "BOM", destination: "EWR", distanceKm: 12520, baseCost: 1050, durationMinutes: 980, airlines: ["AirServe", "United Airlines"] },

  { source: "BLR", destination: "MAA", distanceKm: 290, baseCost: 45, durationMinutes: 50, airlines: ["AirServe", "IndiGo"] },
  { source: "BLR", destination: "CCU", distanceKm: 1560, baseCost: 125, durationMinutes: 150, airlines: ["AirServe"] },
  { source: "BLR", destination: "COK", distanceKm: 370, baseCost: 50, durationMinutes: 60, airlines: ["AirServe", "IndiGo"] },
  { source: "BLR", destination: "GOI", distanceKm: 480, baseCost: 60, durationMinutes: 70, airlines: ["AirServe", "IndiGo"] },
  { source: "BLR", destination: "GOX", distanceKm: 490, baseCost: 62, durationMinutes: 70, airlines: ["AirServe"] },
  { source: "BLR", destination: "TRV", distanceKm: 500, baseCost: 60, durationMinutes: 70, airlines: ["AirServe"] },
  { source: "BLR", destination: "IXE", distanceKm: 310, baseCost: 45, durationMinutes: 55, airlines: ["AirServe"] },
  { source: "BLR", destination: "CJB", distanceKm: 230, baseCost: 40, durationMinutes: 50, airlines: ["AirServe"] },
  { source: "BLR", destination: "IXM", distanceKm: 350, baseCost: 48, durationMinutes: 55, airlines: ["AirServe"] },
  { source: "BLR", destination: "VTZ", distanceKm: 800, baseCost: 80, durationMinutes: 95, airlines: ["AirServe"] },
  { source: "BLR", destination: "BBI", distanceKm: 1200, baseCost: 110, durationMinutes: 125, airlines: ["AirServe"] },
  { source: "BLR", destination: "PAT", distanceKm: 1600, baseCost: 135, durationMinutes: 155, airlines: ["AirServe"] },
  { source: "BLR", destination: "GAU", distanceKm: 2080, baseCost: 160, durationMinutes: 180, airlines: ["AirServe"] },
  { source: "BLR", destination: "SIN", distanceKm: 3170, baseCost: 280, durationMinutes: 275, airlines: ["AirServe", "Singapore Airlines"] },
  { source: "BLR", destination: "DXB", distanceKm: 2700, baseCost: 250, durationMinutes: 250, airlines: ["AirServe", "Emirates"] },
  { source: "BLR", destination: "DOH", distanceKm: 2950, baseCost: 270, durationMinutes: 270, airlines: ["AirServe", "Qatar Airways"] },
  { source: "BLR", destination: "LHR", distanceKm: 8050, baseCost: 730, durationMinutes: 630, airlines: ["AirServe", "British Airways"] },
  { source: "BLR", destination: "CDG", distanceKm: 7850, baseCost: 720, durationMinutes: 620, airlines: ["AirServe", "Air France"] },
  { source: "BLR", destination: "FRA", distanceKm: 7400, baseCost: 700, durationMinutes: 590, airlines: ["AirServe", "Lufthansa"] },
  { source: "BLR", destination: "SYD", distanceKm: 9350, baseCost: 820, durationMinutes: 710, airlines: ["AirServe", "Qantas"] },

  { source: "MAA", destination: "CCU", distanceKm: 1360, baseCost: 120, durationMinutes: 145, airlines: ["AirServe"] },
  { source: "MAA", destination: "COK", distanceKm: 560, baseCost: 65, durationMinutes: 75, airlines: ["AirServe"] },
  { source: "MAA", destination: "TRV", distanceKm: 620, baseCost: 70, durationMinutes: 80, airlines: ["AirServe"] },
  { source: "MAA", destination: "CJB", distanceKm: 425, baseCost: 50, durationMinutes: 60, airlines: ["AirServe"] },
  { source: "MAA", destination: "IXM", distanceKm: 420, baseCost: 50, durationMinutes: 60, airlines: ["AirServe"] },
  { source: "MAA", destination: "IXZ", distanceKm: 1370, baseCost: 125, durationMinutes: 135, airlines: ["AirServe", "Air India"] },
  { source: "MAA", destination: "VTZ", distanceKm: 600, baseCost: 65, durationMinutes: 75, airlines: ["AirServe"] },
  { source: "MAA", destination: "BBI", distanceKm: 1000, baseCost: 95, durationMinutes: 110, airlines: ["AirServe"] },
  { source: "MAA", destination: "SIN", distanceKm: 2900, baseCost: 260, durationMinutes: 255, airlines: ["AirServe", "Singapore Airlines"] },
  { source: "MAA", destination: "KUL", distanceKm: 2630, baseCost: 240, durationMinutes: 235, airlines: ["AirServe", "Malaysia Airlines"] },
  { source: "MAA", destination: "DXB", distanceKm: 2940, baseCost: 265, durationMinutes: 270, airlines: ["AirServe", "Emirates"] },
  { source: "MAA", destination: "LHR", distanceKm: 8220, baseCost: 740, durationMinutes: 640, airlines: ["AirServe", "British Airways"] },

  { source: "CCU", destination: "GAU", distanceKm: 510, baseCost: 55, durationMinutes: 65, airlines: ["AirServe", "IndiGo"] },
  { source: "CCU", destination: "IXB", distanceKm: 450, baseCost: 50, durationMinutes: 60, airlines: ["AirServe", "SpiceJet"] },
  { source: "CCU", destination: "BBI", distanceKm: 360, baseCost: 45, durationMinutes: 50, airlines: ["AirServe"] },
  { source: "CCU", destination: "PAT", distanceKm: 470, baseCost: 50, durationMinutes: 60, airlines: ["AirServe"] },
  { source: "CCU", destination: "IXR", distanceKm: 320, baseCost: 42, durationMinutes: 48, airlines: ["AirServe"] },
  { source: "CCU", destination: "VNS", distanceKm: 630, baseCost: 65, durationMinutes: 75, airlines: ["AirServe"] },
  { source: "CCU", destination: "IXZ", distanceKm: 1300, baseCost: 120, durationMinutes: 130, airlines: ["AirServe", "Air India"] },
  { source: "CCU", destination: "BKK", distanceKm: 1640, baseCost: 170, durationMinutes: 155, airlines: ["AirServe", "Thai Airways"] },
  { source: "CCU", destination: "SIN", distanceKm: 2900, baseCost: 260, durationMinutes: 250, airlines: ["AirServe", "Singapore Airlines"] },
  { source: "CCU", destination: "DXB", distanceKm: 3370, baseCost: 290, durationMinutes: 300, airlines: ["AirServe", "Emirates"] },

  // Global Inter-Continental Backbone Routes
  { source: "DXB", destination: "LHR", distanceKm: 5500, baseCost: 540, durationMinutes: 460, airlines: ["AirServe", "Emirates", "British Airways"] },
  { source: "DXB", destination: "CDG", distanceKm: 5240, baseCost: 520, durationMinutes: 440, airlines: ["AirServe", "Emirates", "Air France"] },
  { source: "DXB", destination: "FRA", distanceKm: 4840, baseCost: 500, durationMinutes: 415, airlines: ["AirServe", "Emirates", "Lufthansa"] },
  { source: "DXB", destination: "AMS", distanceKm: 5170, baseCost: 515, durationMinutes: 435, airlines: ["AirServe", "Emirates", "KLM"] },
  { source: "DXB", destination: "ZRH", distanceKm: 4760, baseCost: 490, durationMinutes: 410, airlines: ["AirServe", "Emirates", "SWISS"] },
  { source: "DXB", destination: "MAD", distanceKm: 5650, baseCost: 550, durationMinutes: 470, airlines: ["AirServe", "Emirates"] },
  { source: "DXB", destination: "FCO", distanceKm: 4320, baseCost: 460, durationMinutes: 375, airlines: ["AirServe", "Emirates"] },
  { source: "DXB", destination: "IST", distanceKm: 3010, baseCost: 320, durationMinutes: 270, airlines: ["AirServe", "Turkish Airlines"] },
  { source: "DXB", destination: "JFK", distanceKm: 11000, baseCost: 950, durationMinutes: 870, airlines: ["AirServe", "Emirates"] },
  { source: "DXB", destination: "LAX", distanceKm: 13420, baseCost: 1150, durationMinutes: 1010, airlines: ["AirServe", "Emirates"] },
  { source: "DXB", destination: "SFO", distanceKm: 13030, baseCost: 1120, durationMinutes: 980, airlines: ["AirServe", "Emirates"] },
  { source: "DXB", destination: "ORD", distanceKm: 11640, baseCost: 990, durationMinutes: 890, airlines: ["AirServe", "Emirates"] },
  { source: "DXB", destination: "YYZ", distanceKm: 11110, baseCost: 960, durationMinutes: 875, airlines: ["AirServe", "Emirates"] },
  { source: "DXB", destination: "SYD", distanceKm: 12040, baseCost: 1040, durationMinutes: 850, airlines: ["AirServe", "Emirates"] },
  { source: "DXB", destination: "MEL", distanceKm: 11600, baseCost: 1010, durationMinutes: 830, airlines: ["AirServe", "Emirates"] },
  { source: "DXB", destination: "CPT", distanceKm: 7640, baseCost: 710, durationMinutes: 580, airlines: ["AirServe", "Emirates"] },
  { source: "DXB", destination: "GRU", distanceKm: 12220, baseCost: 1080, durationMinutes: 900, airlines: ["AirServe", "Emirates"] },
  { source: "DXB", destination: "SIN", distanceKm: 5830, baseCost: 480, durationMinutes: 440, airlines: ["AirServe", "Singapore Airlines", "Emirates"] },
  { source: "DXB", destination: "BKK", distanceKm: 4880, baseCost: 420, durationMinutes: 380, airlines: ["AirServe", "Emirates"] },
  { source: "DXB", destination: "HND", distanceKm: 7950, baseCost: 680, durationMinutes: 600, airlines: ["AirServe", "Emirates"] },

  { source: "SIN", destination: "LHR", distanceKm: 10880, baseCost: 890, durationMinutes: 830, airlines: ["AirServe", "Singapore Airlines", "British Airways"] },
  { source: "SIN", destination: "CDG", distanceKm: 10730, baseCost: 880, durationMinutes: 815, airlines: ["AirServe", "Singapore Airlines", "Air France"] },
  { source: "SIN", destination: "FRA", distanceKm: 10280, baseCost: 850, durationMinutes: 790, airlines: ["AirServe", "Singapore Airlines", "Lufthansa"] },
  { source: "SIN", destination: "AMS", distanceKm: 10520, baseCost: 870, durationMinutes: 805, airlines: ["AirServe", "Singapore Airlines", "KLM"] },
  { source: "SIN", destination: "ZRH", distanceKm: 10300, baseCost: 860, durationMinutes: 795, airlines: ["AirServe", "Singapore Airlines", "SWISS"] },
  { source: "SIN", destination: "SYD", distanceKm: 6300, baseCost: 560, durationMinutes: 465, airlines: ["AirServe", "Singapore Airlines", "Qantas"] },
  { source: "SIN", destination: "MEL", distanceKm: 6030, baseCost: 540, durationMinutes: 445, airlines: ["AirServe", "Singapore Airlines", "Qantas"] },
  { source: "SIN", destination: "HND", distanceKm: 5310, baseCost: 490, durationMinutes: 410, airlines: ["AirServe", "Singapore Airlines", "ANA"] },
  { source: "SIN", destination: "NRT", distanceKm: 5360, baseCost: 490, durationMinutes: 415, airlines: ["AirServe", "Singapore Airlines", "Japan Airlines"] },
  { source: "SIN", destination: "ICN", distanceKm: 4660, baseCost: 440, durationMinutes: 370, airlines: ["AirServe", "Singapore Airlines", "Korean Air"] },
  { source: "SIN", destination: "BKK", distanceKm: 1420, baseCost: 150, durationMinutes: 140, airlines: ["AirServe", "Singapore Airlines", "Thai Airways"] },
  { source: "SIN", destination: "KUL", distanceKm: 300, baseCost: 45, durationMinutes: 55, airlines: ["AirServe", "Singapore Airlines", "Malaysia Airlines"] },
  { source: "SIN", destination: "SFO", distanceKm: 13590, baseCost: 1140, durationMinutes: 930, airlines: ["AirServe", "Singapore Airlines"] },
  { source: "SIN", destination: "LAX", distanceKm: 14110, baseCost: 1180, durationMinutes: 980, airlines: ["AirServe", "Singapore Airlines"] },
  { source: "SIN", destination: "JFK", distanceKm: 15350, baseCost: 1320, durationMinutes: 1110, airlines: ["AirServe", "Singapore Airlines"] },

  { source: "LHR", destination: "JFK", distanceKm: 5540, baseCost: 510, durationMinutes: 470, airlines: ["AirServe", "British Airways", "Virgin Atlantic"] },
  { source: "LHR", destination: "LAX", distanceKm: 8760, baseCost: 740, durationMinutes: 670, airlines: ["AirServe", "British Airways", "American Airlines"] },
  { source: "LHR", destination: "SFO", distanceKm: 8620, baseCost: 730, durationMinutes: 660, airlines: ["AirServe", "British Airways"] },
  { source: "LHR", destination: "ORD", distanceKm: 6360, baseCost: 580, durationMinutes: 520, airlines: ["AirServe", "British Airways", "United Airlines"] },
  { source: "LHR", destination: "YYZ", distanceKm: 5720, baseCost: 530, durationMinutes: 480, airlines: ["AirServe", "British Airways", "Air Canada"] },
  { source: "LHR", destination: "CDG", distanceKm: 350, baseCost: 65, durationMinutes: 70, airlines: ["AirServe", "British Airways", "Air France"] },
  { source: "LHR", destination: "FRA", distanceKm: 650, baseCost: 85, durationMinutes: 95, airlines: ["AirServe", "British Airways", "Lufthansa"] },
  { source: "LHR", destination: "AMS", distanceKm: 370, baseCost: 68, durationMinutes: 75, airlines: ["AirServe", "British Airways", "KLM"] },
  { source: "LHR", destination: "MAD", distanceKm: 1260, baseCost: 115, durationMinutes: 135, airlines: ["AirServe", "Iberia", "British Airways"] },
  { source: "LHR", destination: "FCO", distanceKm: 1440, baseCost: 125, durationMinutes: 145, airlines: ["AirServe", "British Airways", "ITA Airways"] },
  { source: "LHR", destination: "ZRH", distanceKm: 780, baseCost: 95, durationMinutes: 105, airlines: ["AirServe", "SWISS", "British Airways"] },
  { source: "LHR", destination: "HND", distanceKm: 9590, baseCost: 820, durationMinutes: 720, airlines: ["AirServe", "British Airways", "Japan Airlines"] },
  { source: "LHR", destination: "SYD", distanceKm: 17020, baseCost: 1390, durationMinutes: 1320, airlines: ["AirServe", "Qantas", "British Airways"] },
  { source: "LHR", destination: "CPT", distanceKm: 9670, baseCost: 830, durationMinutes: 710, airlines: ["AirServe", "British Airways"] },

  { source: "JFK", destination: "LAX", distanceKm: 3980, baseCost: 320, durationMinutes: 340, airlines: ["AirServe", "Delta", "American Airlines"] },
  { source: "JFK", destination: "SFO", distanceKm: 4150, baseCost: 330, durationMinutes: 360, airlines: ["AirServe", "Delta", "United Airlines"] },
  { source: "JFK", destination: "ORD", distanceKm: 1190, baseCost: 110, durationMinutes: 135, airlines: ["AirServe", "American Airlines"] },
  { source: "JFK", destination: "YYZ", distanceKm: 590, baseCost: 75, durationMinutes: 85, airlines: ["AirServe", "Air Canada"] },
  { source: "JFK", destination: "CDG", distanceKm: 5840, baseCost: 530, durationMinutes: 440, airlines: ["AirServe", "Air France", "Delta"] },
  { source: "JFK", destination: "FRA", distanceKm: 6200, baseCost: 550, durationMinutes: 465, airlines: ["AirServe", "Lufthansa", "Delta"] },
  { source: "JFK", destination: "GRU", distanceKm: 7680, baseCost: 690, durationMinutes: 580, airlines: ["AirServe", "LATAM", "Delta"] },
  { source: "JFK", destination: "HND", distanceKm: 10860, baseCost: 910, durationMinutes: 840, airlines: ["AirServe", "ANA", "Japan Airlines"] },
];

export function getInitialUsers() {
  const salt = bcrypt.genSaltSync(10);
  return [
    {
      id: "USR-0001",
      username: "admin",
      passwordHash: bcrypt.hashSync("Admin@123", salt),
      role: "ADMIN",
      name: "Chief Flight Controller",
      email: "admin@airserve.aero",
      phone: "+1 800 247 7378",
      passengerId: null,
      createdAt: "2026-08-01T08:00:00.000Z",
    },
    {
      id: "USR-1001",
      username: "alex.miller",
      passwordHash: bcrypt.hashSync("Pass@123", salt),
      role: "PASSENGER",
      name: "Captain Alex Miller",
      email: "alex.miller@skyline.org",
      phone: "+1 555 019 2831",
      passengerId: "PAS-1001",
      createdAt: "2026-08-10T10:30:00.000Z",
    },
    {
      id: "USR-1002",
      username: "sarah.chen",
      passwordHash: bcrypt.hashSync("Pass@123", salt),
      role: "PASSENGER",
      name: "Dr. Sarah Chen",
      email: "sarah.chen@techglobal.io",
      phone: "+65 9123 4567",
      passengerId: "PAS-1002",
      createdAt: "2026-08-12T14:15:00.000Z",
    },
    {
      id: "USR-1003",
      username: "priya.sharma",
      passwordHash: bcrypt.hashSync("Pass@123", salt),
      role: "PASSENGER",
      name: "Priya Sharma",
      email: "priya.sharma@nexus.in",
      phone: "+91 98480 22334",
      passengerId: "PAS-1003",
      createdAt: "2026-08-15T09:00:00.000Z",
    },
    {
      id: "USR-1004",
      username: "rahul.verma",
      passwordHash: bcrypt.hashSync("Pass@123", salt),
      role: "PASSENGER",
      name: "Rahul Verma",
      email: "rahul.v@innovate.co",
      phone: "+91 99887 11223",
      passengerId: "PAS-1004",
      createdAt: "2026-08-18T16:45:00.000Z",
    },
  ];
}

export function getInitialPassengers() {
  return [
    {
      id: "PAS-1001",
      userId: "USR-1001",
      name: "Captain Alex Miller",
      email: "alex.miller@skyline.org",
      phone: "+1 555 019 2831",
      passportNumber: "US9842100A",
      nationality: "United States",
      tier: "VIP",
      loyaltyPoints: 45200,
      createdAt: "2026-08-10T10:30:00.000Z",
    },
    {
      id: "PAS-1002",
      userId: "USR-1002",
      name: "Dr. Sarah Chen",
      email: "sarah.chen@techglobal.io",
      phone: "+65 9123 4567",
      passportNumber: "SG8812903K",
      nationality: "Singapore",
      tier: "GOLD",
      loyaltyPoints: 28900,
      createdAt: "2026-08-12T14:15:00.000Z",
    },
    {
      id: "PAS-1003",
      userId: "USR-1003",
      name: "Priya Sharma",
      email: "priya.sharma@nexus.in",
      phone: "+91 98480 22334",
      passportNumber: "IN7729011P",
      nationality: "India",
      tier: "BUSINESS",
      loyaltyPoints: 12400,
      createdAt: "2026-08-15T09:00:00.000Z",
    },
    {
      id: "PAS-1004",
      userId: "USR-1004",
      name: "Rahul Verma",
      email: "rahul.v@innovate.co",
      phone: "+91 99887 11223",
      passportNumber: "IN6612099R",
      nationality: "India",
      tier: "STANDARD",
      loyaltyPoints: 3200,
      createdAt: "2026-08-18T16:45:00.000Z",
    },
    {
      id: "PAS-1005",
      userId: null,
      name: "Elena Rostova",
      email: "elena.rostova@globe.eu",
      phone: "+44 20 7946 0991",
      passportNumber: "GB4490123L",
      nationality: "United Kingdom",
      tier: "GOLD",
      loyaltyPoints: 18500,
      createdAt: "2026-08-20T11:20:00.000Z",
    },
    {
      id: "PAS-1006",
      userId: null,
      name: "Marcus Aurelius Vance",
      email: "marcus.v@heritage.org",
      phone: "+1 555 771 9021",
      passportNumber: "US1109482V",
      nationality: "United States",
      tier: "VIP",
      loyaltyPoints: 61000,
      createdAt: "2026-08-21T13:40:00.000Z",
    },
  ];
}

export interface FlightTemplate {
  baseFlightNumber: string;
  airline: string;
  sourceAirport: string;
  destinationAirport: string;
  departureTime: string;
  arrivalTime: string;
  duration: string;
  aircraft: string;
  terminal: string;
  gate: string;
  totalSeats: number;
  ticketPrice: number;
  class: string;
  status: "SCHEDULED" | "BOARDING" | "DEPARTED" | "DELAYED" | "CANCELLED";
}

// Master Schedule Route Templates (Standard Commercial Aviation Daily Network)
export const standardFlightTemplates: FlightTemplate[] = [
  // HYD <-> DEL
  { baseFlightNumber: "AS-101", airline: "AirServe Express", sourceAirport: "HYD", destinationAirport: "DEL", departureTime: "06:30", arrivalTime: "08:45", duration: "2h 15m", aircraft: "Boeing 787-9 Dreamliner", terminal: "T1", gate: "G12", totalSeats: 30, ticketPrice: 110, class: "Economy", status: "SCHEDULED" },
  { baseFlightNumber: "AS-102", airline: "AirServe Express", sourceAirport: "DEL", destinationAirport: "HYD", departureTime: "18:15", arrivalTime: "20:30", duration: "2h 15m", aircraft: "Boeing 787-9 Dreamliner", terminal: "T3", gate: "G04", totalSeats: 30, ticketPrice: 115, class: "Economy", status: "SCHEDULED" },
  { baseFlightNumber: "AI-803", airline: "Air India", sourceAirport: "HYD", destinationAirport: "DEL", departureTime: "11:00", arrivalTime: "13:15", duration: "2h 15m", aircraft: "Airbus A320neo", terminal: "T1", gate: "G18", totalSeats: 30, ticketPrice: 105, class: "Economy", status: "SCHEDULED" },
  { baseFlightNumber: "6E-205", airline: "IndiGo", sourceAirport: "HYD", destinationAirport: "DEL", departureTime: "16:45", arrivalTime: "19:00", duration: "2h 15m", aircraft: "Airbus A321neo", terminal: "T1", gate: "G22", totalSeats: 30, ticketPrice: 95, class: "Economy", status: "SCHEDULED" },

  // HYD <-> BOM
  { baseFlightNumber: "AS-103", airline: "AirServe Express", sourceAirport: "HYD", destinationAirport: "BOM", departureTime: "07:00", arrivalTime: "08:25", duration: "1h 25m", aircraft: "Boeing 737 MAX", terminal: "T1", gate: "G05", totalSeats: 28, ticketPrice: 75, class: "Economy", status: "SCHEDULED" },
  { baseFlightNumber: "AS-104", airline: "AirServe Express", sourceAirport: "BOM", destinationAirport: "HYD", departureTime: "19:30", arrivalTime: "20:55", duration: "1h 25m", aircraft: "Boeing 737 MAX", terminal: "T2", gate: "G11", totalSeats: 28, ticketPrice: 75, class: "Economy", status: "SCHEDULED" },

  // HYD <-> BLR
  { baseFlightNumber: "AS-105", airline: "AirServe Express", sourceAirport: "HYD", destinationAirport: "BLR", departureTime: "08:30", arrivalTime: "09:40", duration: "1h 10m", aircraft: "Airbus A321neo", terminal: "T1", gate: "G03", totalSeats: 30, ticketPrice: 60, class: "Economy", status: "SCHEDULED" },
  { baseFlightNumber: "AS-410", airline: "AirServe Express", sourceAirport: "BLR", destinationAirport: "HYD", departureTime: "14:20", arrivalTime: "15:30", duration: "1h 10m", aircraft: "Airbus A321neo", terminal: "T2", gate: "G15", totalSeats: 30, ticketPrice: 65, class: "Economy", status: "SCHEDULED" },

  // HYD <-> MAA
  { baseFlightNumber: "AS-107", airline: "AirServe Express", sourceAirport: "HYD", destinationAirport: "MAA", departureTime: "09:15", arrivalTime: "10:30", duration: "1h 15m", aircraft: "Airbus A320neo", terminal: "T1", gate: "G07", totalSeats: 26, ticketPrice: 65, class: "Economy", status: "SCHEDULED" },
  { baseFlightNumber: "AS-108", airline: "AirServe Express", sourceAirport: "MAA", destinationAirport: "HYD", departureTime: "16:00", arrivalTime: "17:15", duration: "1h 15m", aircraft: "Airbus A320neo", terminal: "T1", gate: "G09", totalSeats: 26, ticketPrice: 65, class: "Economy", status: "SCHEDULED" },

  // HYD <-> DXB
  { baseFlightNumber: "AS-204", airline: "AirServe Express", sourceAirport: "HYD", destinationAirport: "DXB", departureTime: "10:00", arrivalTime: "12:30", duration: "4h 00m", aircraft: "Airbus A350-900", terminal: "T1", gate: "G08", totalSeats: 24, ticketPrice: 260, class: "Business", status: "SCHEDULED" },
  { baseFlightNumber: "EK-527", airline: "Emirates", sourceAirport: "HYD", destinationAirport: "DXB", departureTime: "21:45", arrivalTime: "00:15", duration: "4h 00m", aircraft: "Boeing 777-300ER", terminal: "T1", gate: "G16", totalSeats: 28, ticketPrice: 310, class: "First Class", status: "SCHEDULED" },
  { baseFlightNumber: "EK-528", airline: "Emirates", sourceAirport: "DXB", destinationAirport: "HYD", departureTime: "03:30", arrivalTime: "08:45", duration: "3h 45m", aircraft: "Boeing 777-300ER", terminal: "T3", gate: "G02", totalSeats: 28, ticketPrice: 290, class: "Business", status: "SCHEDULED" },

  // HYD <-> SIN
  { baseFlightNumber: "AS-206", airline: "AirServe Express", sourceAirport: "HYD", destinationAirport: "SIN", departureTime: "23:15", arrivalTime: "06:30", duration: "4h 45m", aircraft: "Boeing 787-9 Dreamliner", terminal: "T1", gate: "G19", totalSeats: 28, ticketPrice: 290, class: "Business", status: "SCHEDULED" },
  { baseFlightNumber: "SQ-511", airline: "Singapore Airlines", sourceAirport: "HYD", destinationAirport: "SIN", departureTime: "11:30", arrivalTime: "18:45", duration: "4h 45m", aircraft: "Airbus A350-900", terminal: "T1", gate: "G14", totalSeats: 30, ticketPrice: 280, class: "Economy", status: "SCHEDULED" },

  // DEL <-> BOM
  { baseFlightNumber: "AI-801", airline: "Air India", sourceAirport: "DEL", destinationAirport: "BOM", departureTime: "09:00", arrivalTime: "11:15", duration: "2h 15m", aircraft: "Airbus A320neo", terminal: "T3", gate: "G18", totalSeats: 30, ticketPrice: 105, class: "Economy", status: "SCHEDULED" },
  { baseFlightNumber: "AS-301", airline: "AirServe Express", sourceAirport: "DEL", destinationAirport: "BOM", departureTime: "17:30", arrivalTime: "19:45", duration: "2h 15m", aircraft: "Boeing 787-9 Dreamliner", terminal: "T3", gate: "G06", totalSeats: 30, ticketPrice: 110, class: "Business", status: "SCHEDULED" },
  { baseFlightNumber: "6E-5002", airline: "IndiGo", sourceAirport: "BOM", destinationAirport: "DEL", departureTime: "06:15", arrivalTime: "08:30", duration: "2h 15m", aircraft: "Airbus A321neo", terminal: "T2", gate: "G12", totalSeats: 30, ticketPrice: 98, class: "Economy", status: "SCHEDULED" },

  // DEL <-> BLR
  { baseFlightNumber: "AS-303", airline: "AirServe Express", sourceAirport: "DEL", destinationAirport: "BLR", departureTime: "07:15", arrivalTime: "10:00", duration: "2h 45m", aircraft: "Airbus A321neo", terminal: "T3", gate: "G10", totalSeats: 30, ticketPrice: 130, class: "Economy", status: "SCHEDULED" },
  { baseFlightNumber: "AI-505", airline: "Air India", sourceAirport: "BLR", destinationAirport: "DEL", departureTime: "16:00", arrivalTime: "18:45", duration: "2h 45m", aircraft: "Airbus A320neo", terminal: "T2", gate: "G08", totalSeats: 30, ticketPrice: 125, class: "Economy", status: "SCHEDULED" },

  // DEL <-> CCU
  { baseFlightNumber: "AS-307", airline: "AirServe Express", sourceAirport: "DEL", destinationAirport: "CCU", departureTime: "08:00", arrivalTime: "10:20", duration: "2h 20m", aircraft: "Airbus A320neo", terminal: "T3", gate: "G15", totalSeats: 28, ticketPrice: 115, class: "Economy", status: "SCHEDULED" },
  { baseFlightNumber: "AI-701", airline: "Air India", sourceAirport: "CCU", destinationAirport: "DEL", departureTime: "13:30", arrivalTime: "15:50", duration: "2h 20m", aircraft: "Airbus A320neo", terminal: "T2", gate: "G04", totalSeats: 28, ticketPrice: 110, class: "Economy", status: "SCHEDULED" },

  // DEL <-> DXB
  { baseFlightNumber: "AS-501", airline: "AirServe Express", sourceAirport: "DEL", destinationAirport: "DXB", departureTime: "09:30", arrivalTime: "11:45", duration: "3h 45m", aircraft: "Airbus A350-900", terminal: "T3", gate: "G20", totalSeats: 26, ticketPrice: 220, class: "Business", status: "SCHEDULED" },
  { baseFlightNumber: "EK-511", airline: "Emirates", sourceAirport: "DEL", destinationAirport: "DXB", departureTime: "14:00", arrivalTime: "16:15", duration: "3h 45m", aircraft: "Boeing 777-300ER", terminal: "T3", gate: "G24", totalSeats: 30, ticketPrice: 380, class: "First Class", status: "SCHEDULED" },

  // DEL <-> LHR
  { baseFlightNumber: "AS-520", airline: "AirServe Express", sourceAirport: "DEL", destinationAirport: "LHR", departureTime: "02:10", arrivalTime: "07:00", duration: "9h 20m", aircraft: "Boeing 787-9 Dreamliner", terminal: "T3", gate: "G32", totalSeats: 26, ticketPrice: 690, class: "Business", status: "SCHEDULED" },
  { baseFlightNumber: "BA-142", airline: "British Airways", sourceAirport: "DEL", destinationAirport: "LHR", departureTime: "08:30", arrivalTime: "13:20", duration: "9h 20m", aircraft: "Boeing 787-10", terminal: "T3", gate: "G34", totalSeats: 28, ticketPrice: 850, class: "First Class", status: "SCHEDULED" },
  { baseFlightNumber: "AI-112", airline: "Air India", sourceAirport: "LHR", destinationAirport: "DEL", departureTime: "21:30", arrivalTime: "11:00", duration: "8h 00m", aircraft: "Boeing 787-8", terminal: "T2", gate: "G11", totalSeats: 30, ticketPrice: 490, class: "Economy", status: "SCHEDULED" },

  // DEL <-> JFK
  { baseFlightNumber: "AS-550", airline: "AirServe Express", sourceAirport: "DEL", destinationAirport: "JFK", departureTime: "01:30", arrivalTime: "07:00", duration: "15h 00m", aircraft: "Boeing 777-300ER", terminal: "T3", gate: "G30", totalSeats: 28, ticketPrice: 980, class: "Business", status: "SCHEDULED" },
  { baseFlightNumber: "AI-101", airline: "Air India", sourceAirport: "DEL", destinationAirport: "JFK", departureTime: "03:00", arrivalTime: "08:30", duration: "15h 00m", aircraft: "Boeing 777-200LR", terminal: "T3", gate: "G28", totalSeats: 32, ticketPrice: 750, class: "Economy", status: "SCHEDULED" },

  // BOM <-> BLR
  { baseFlightNumber: "AS-401", airline: "AirServe Express", sourceAirport: "BOM", destinationAirport: "BLR", departureTime: "06:45", arrivalTime: "08:25", duration: "1h 40m", aircraft: "Airbus A320neo", terminal: "T2", gate: "G06", totalSeats: 30, ticketPrice: 85, class: "Economy", status: "SCHEDULED" },
  { baseFlightNumber: "6E-344", airline: "IndiGo", sourceAirport: "BLR", destinationAirport: "BOM", departureTime: "15:00", arrivalTime: "16:40", duration: "1h 40m", aircraft: "Airbus A321neo", terminal: "T2", gate: "G14", totalSeats: 30, ticketPrice: 80, class: "Economy", status: "SCHEDULED" },

  // BOM <-> DXB
  { baseFlightNumber: "EK-502", airline: "Emirates", sourceAirport: "BOM", destinationAirport: "DXB", departureTime: "04:30", arrivalTime: "06:15", duration: "3h 15m", aircraft: "Boeing 777-300ER", terminal: "T2", gate: "G09", totalSeats: 28, ticketPrice: 210, class: "Business", status: "SCHEDULED" },
  { baseFlightNumber: "AS-503", airline: "AirServe Express", sourceAirport: "BOM", destinationAirport: "DXB", departureTime: "16:00", arrivalTime: "17:45", duration: "3h 15m", aircraft: "Airbus A350-900", terminal: "T2", gate: "G16", totalSeats: 26, ticketPrice: 195, class: "Economy", status: "SCHEDULED" },

  // BOM <-> LHR
  { baseFlightNumber: "AS-522", airline: "AirServe Express", sourceAirport: "BOM", destinationAirport: "LHR", departureTime: "03:00", arrivalTime: "07:50", duration: "9h 50m", aircraft: "Boeing 787-9 Dreamliner", terminal: "T2", gate: "G22", totalSeats: 26, ticketPrice: 690, class: "Business", status: "SCHEDULED" },
  { baseFlightNumber: "BA-198", airline: "British Airways", sourceAirport: "BOM", destinationAirport: "LHR", departureTime: "13:15", arrivalTime: "18:05", duration: "9h 50m", aircraft: "Boeing 777-300ER", terminal: "T2", gate: "G20", totalSeats: 28, ticketPrice: 880, class: "First Class", status: "SCHEDULED" },

  // BOM <-> SIN
  { baseFlightNumber: "AS-305", airline: "AirServe Express", sourceAirport: "BOM", destinationAirport: "SIN", departureTime: "23:00", arrivalTime: "07:15", duration: "5h 45m", aircraft: "Boeing 777-300ER", terminal: "T2", gate: "G21", totalSeats: 28, ticketPrice: 340, class: "First Class", status: "SCHEDULED" },
  { baseFlightNumber: "SQ-421", airline: "Singapore Airlines", sourceAirport: "BOM", destinationAirport: "SIN", departureTime: "11:45", arrivalTime: "19:55", duration: "5h 40m", aircraft: "Airbus A350-900", terminal: "T2", gate: "G14", totalSeats: 30, ticketPrice: 320, class: "Economy", status: "SCHEDULED" },

  // BLR <-> MAA
  { baseFlightNumber: "AS-411", airline: "AirServe Express", sourceAirport: "BLR", destinationAirport: "MAA", departureTime: "07:30", arrivalTime: "08:20", duration: "0h 50m", aircraft: "Airbus A320neo", terminal: "T2", gate: "G05", totalSeats: 28, ticketPrice: 45, class: "Economy", status: "SCHEDULED" },
  { baseFlightNumber: "6E-108", airline: "IndiGo", sourceAirport: "MAA", destinationAirport: "BLR", departureTime: "12:00", arrivalTime: "12:50", duration: "0h 50m", aircraft: "Airbus A320neo", terminal: "T1", gate: "G08", totalSeats: 30, ticketPrice: 40, class: "Economy", status: "SCHEDULED" },

  // BLR <-> SIN
  { baseFlightNumber: "AS-417", airline: "AirServe Express", sourceAirport: "BLR", destinationAirport: "SIN", departureTime: "22:30", arrivalTime: "05:45", duration: "4h 45m", aircraft: "Boeing 787-9 Dreamliner", terminal: "T2", gate: "G17", totalSeats: 28, ticketPrice: 280, class: "Business", status: "SCHEDULED" },
  { baseFlightNumber: "SQ-503", airline: "Singapore Airlines", sourceAirport: "BLR", destinationAirport: "SIN", departureTime: "11:00", arrivalTime: "18:15", duration: "4h 45m", aircraft: "Airbus A350-900", terminal: "T2", gate: "G19", totalSeats: 30, ticketPrice: 270, class: "Economy", status: "SCHEDULED" },

  // BLR <-> DXB
  { baseFlightNumber: "AS-419", airline: "AirServe Express", sourceAirport: "BLR", destinationAirport: "DXB", departureTime: "10:30", arrivalTime: "13:10", duration: "4h 10m", aircraft: "Airbus A350-900", terminal: "T2", gate: "G21", totalSeats: 26, ticketPrice: 250, class: "Business", status: "SCHEDULED" },
  { baseFlightNumber: "EK-565", airline: "Emirates", sourceAirport: "BLR", destinationAirport: "DXB", departureTime: "20:30", arrivalTime: "23:10", duration: "4h 10m", aircraft: "Boeing 777-300ER", terminal: "T2", gate: "G23", totalSeats: 28, ticketPrice: 320, class: "First Class", status: "SCHEDULED" },

  // MAA <-> CCU
  { baseFlightNumber: "AS-421", airline: "AirServe Express", sourceAirport: "MAA", destinationAirport: "CCU", departureTime: "08:45", arrivalTime: "11:10", duration: "2h 25m", aircraft: "Airbus A320neo", terminal: "T1", gate: "G11", totalSeats: 28, ticketPrice: 120, class: "Economy", status: "SCHEDULED" },

  // MAA <-> SIN
  { baseFlightNumber: "AS-423", airline: "AirServe Express", sourceAirport: "MAA", destinationAirport: "SIN", departureTime: "09:30", arrivalTime: "16:15", duration: "4h 15m", aircraft: "Airbus A350-900", terminal: "T1", gate: "G15", totalSeats: 26, ticketPrice: 260, class: "Business", status: "SCHEDULED" },
  { baseFlightNumber: "SQ-527", airline: "Singapore Airlines", sourceAirport: "MAA", destinationAirport: "SIN", departureTime: "23:15", arrivalTime: "06:00", duration: "4h 15m", aircraft: "Boeing 787-10", terminal: "T1", gate: "G17", totalSeats: 30, ticketPrice: 250, class: "Economy", status: "SCHEDULED" },

  // DXB <-> LHR
  { baseFlightNumber: "EK-001", airline: "Emirates", sourceAirport: "DXB", destinationAirport: "LHR", departureTime: "07:45", arrivalTime: "12:25", duration: "7h 40m", aircraft: "Airbus A380-800", terminal: "T3", gate: "G05", totalSeats: 32, ticketPrice: 650, class: "First Class", status: "SCHEDULED" },
  { baseFlightNumber: "BA-108", airline: "British Airways", sourceAirport: "DXB", destinationAirport: "LHR", departureTime: "10:00", arrivalTime: "14:40", duration: "7h 40m", aircraft: "Boeing 777-300ER", terminal: "T1", gate: "G12", totalSeats: 28, ticketPrice: 580, class: "Business", status: "SCHEDULED" },

  // DXB <-> JFK
  { baseFlightNumber: "AS-630", airline: "AirServe Express", sourceAirport: "DXB", destinationAirport: "JFK", departureTime: "08:30", arrivalTime: "14:15", duration: "14h 45m", aircraft: "Airbus A380-800", terminal: "T3", gate: "G01", totalSeats: 32, ticketPrice: 990, class: "First Class", status: "SCHEDULED" },
  { baseFlightNumber: "EK-201", airline: "Emirates", sourceAirport: "DXB", destinationAirport: "JFK", departureTime: "02:25", arrivalTime: "08:10", duration: "14h 45m", aircraft: "Airbus A380-800", terminal: "T3", gate: "G03", totalSeats: 32, ticketPrice: 920, class: "Business", status: "SCHEDULED" },

  // LHR <-> JFK
  { baseFlightNumber: "BA-117", airline: "British Airways", sourceAirport: "LHR", destinationAirport: "JFK", departureTime: "08:45", arrivalTime: "11:35", duration: "7h 50m", aircraft: "Boeing 777-300ER", terminal: "T5", gate: "G11", totalSeats: 30, ticketPrice: 590, class: "First Class", status: "SCHEDULED" },
  { baseFlightNumber: "VS-003", airline: "Virgin Atlantic", sourceAirport: "LHR", destinationAirport: "JFK", departureTime: "14:00", arrivalTime: "16:50", duration: "7h 50m", aircraft: "Airbus A350-1000", terminal: "T3", gate: "G19", totalSeats: 28, ticketPrice: 520, class: "Business", status: "SCHEDULED" },

  // SIN <-> LHR
  { baseFlightNumber: "SQ-318", airline: "Singapore Airlines", sourceAirport: "SIN", destinationAirport: "LHR", departureTime: "12:45", arrivalTime: "19:15", duration: "13h 30m", aircraft: "Airbus A380-800", terminal: "T3", gate: "G08", totalSeats: 32, ticketPrice: 890, class: "Business", status: "SCHEDULED" },
  { baseFlightNumber: "BA-012", airline: "British Airways", sourceAirport: "SIN", destinationAirport: "LHR", departureTime: "23:15", arrivalTime: "05:45", duration: "13h 30m", aircraft: "Boeing 777-300ER", terminal: "T1", gate: "G14", totalSeats: 30, ticketPrice: 950, class: "First Class", status: "SCHEDULED" },
];

/**
 * Generate full scheduled flights for any requested date (YYYY-MM-DD).
 * Seamlessly formats flight numbers, arrival dates, and initial seat occupancy.
 */
export function generateFlightsForDate(dateStr: string): any[] {
  const parts = dateStr.split("-");
  const monthDay = parts.length === 3 ? `${parts[1]}${parts[2]}` : dateStr.replace(/[^0-9]/g, "").slice(-4);
  const isTargetDate2 = dateStr === "2026-09-02";
  const isTargetDate3 = dateStr === "2026-09-03";
  const isTargetDate4 = dateStr === "2026-09-04";
  const isTargetDate5 = dateStr === "2026-09-05";

  return standardFlightTemplates.map((template) => {
    // Determine unique flight key:
    // Keep exact original primary keys for seeded flights to maintain FK relations with initial bookings
    let flightNumber = template.baseFlightNumber;
    if (isTargetDate2) {
      if (["AS-101", "AS-102", "AS-410", "AI-801"].includes(template.baseFlightNumber)) {
        flightNumber = template.baseFlightNumber;
      } else {
        flightNumber = `${template.baseFlightNumber}-${monthDay}`;
      }
    } else if (isTargetDate3) {
      if (["AS-204", "AS-305", "EK-502", "SQ-421"].includes(template.baseFlightNumber)) {
        flightNumber = template.baseFlightNumber;
      } else {
        flightNumber = `${template.baseFlightNumber}-${monthDay}`;
      }
    } else if (isTargetDate4) {
      if (["AS-520"].includes(template.baseFlightNumber)) {
        flightNumber = template.baseFlightNumber;
      } else {
        flightNumber = `${template.baseFlightNumber}-${monthDay}`;
      }
    } else if (isTargetDate5) {
      if (["AS-630"].includes(template.baseFlightNumber)) {
        flightNumber = template.baseFlightNumber;
      } else {
        flightNumber = `${template.baseFlightNumber}-${monthDay}`;
      }
    } else {
      flightNumber = `${template.baseFlightNumber}-${monthDay}`;
    }

    // Determine available seats
    let availableSeats = template.totalSeats - Math.floor(Math.random() * 6);
    if (flightNumber === "AS-101") availableSeats = 26;
    if (flightNumber === "AS-102") availableSeats = 28;
    if (flightNumber === "AS-204") availableSeats = 0; // Fully booked for waiting list demo
    if (flightNumber === "AS-305") availableSeats = 19;
    if (flightNumber === "AS-410") availableSeats = 27;
    if (flightNumber === "AS-520") availableSeats = 21;
    if (flightNumber === "AS-630") availableSeats = 24;

    // Arrival date (handling overnight flights)
    const depHour = parseInt(template.departureTime.split(":")[0], 10);
    const arrHour = parseInt(template.arrivalTime.split(":")[0], 10);
    let arrivalDate = dateStr;
    if (arrHour < depHour) {
      // Crosses midnight
      const d = new Date(`${dateStr}T00:00:00Z`);
      d.setUTCDate(d.getUTCDate() + 1);
      arrivalDate = d.toISOString().split("T")[0];
    }

    return {
      flightNumber,
      airline: template.airline,
      sourceAirport: template.sourceAirport,
      destinationAirport: template.destinationAirport,
      departureDate: dateStr,
      departureTime: template.departureTime,
      arrivalDate,
      arrivalTime: template.arrivalTime,
      duration: template.duration,
      aircraft: template.aircraft,
      terminal: template.terminal,
      gate: template.gate,
      totalSeats: template.totalSeats,
      availableSeats: Math.max(0, Math.min(template.totalSeats, availableSeats)),
      ticketPrice: template.ticketPrice,
      class: template.class,
      status: flightNumber === "AS-204" ? "BOARDING" : template.status,
    };
  });
}

export function getInitialFlights() {
  // Pre-seed a rich flight calendar across multiple active dates around September 2026
  const dates = [
    "2026-09-01",
    "2026-09-02",
    "2026-09-03",
    "2026-09-04",
    "2026-09-05",
    "2026-09-06",
    "2026-09-07",
    "2026-09-08",
    "2026-09-09",
    "2026-09-10",
    "2026-09-11",
    "2026-09-12",
    "2026-09-13",
    "2026-09-14",
  ];

  const allFlights: any[] = [];
  for (const d of dates) {
    allFlights.push(...generateFlightsForDate(d));
  }
  return allFlights;
}

export function getInitialBookings() {
  return [
    {
      bookingId: "BK-8001",
      passengerId: "PAS-1001",
      flightNumber: "AS-101",
      passengerName: "Captain Alex Miller",
      bookingDate: "2026-08-25T10:00:00.000Z",
      seatNumber: "1A",
      class: "Business",
      ticketPrice: 160,
      paymentStatus: "PAID",
      bookingStatus: "CONFIRMED",
    },
    {
      bookingId: "BK-8002",
      passengerId: "PAS-1002",
      flightNumber: "AS-101",
      passengerName: "Dr. Sarah Chen",
      bookingDate: "2026-08-26T12:30:00.000Z",
      seatNumber: "2B",
      class: "Economy",
      ticketPrice: 110,
      paymentStatus: "PAID",
      bookingStatus: "CONFIRMED",
    },
    {
      bookingId: "BK-8003",
      passengerId: "PAS-1003",
      flightNumber: "AS-101",
      passengerName: "Priya Sharma",
      bookingDate: "2026-08-26T15:45:00.000Z",
      seatNumber: "3C",
      class: "Economy",
      ticketPrice: 110,
      paymentStatus: "PAID",
      bookingStatus: "CONFIRMED",
    },
    {
      bookingId: "BK-8004",
      passengerId: "PAS-1004",
      flightNumber: "AS-101",
      passengerName: "Rahul Verma",
      bookingDate: "2026-08-27T09:15:00.000Z",
      seatNumber: "4D",
      class: "Economy",
      ticketPrice: 110,
      paymentStatus: "PAID",
      bookingStatus: "CONFIRMED",
    },
    {
      bookingId: "BK-8005",
      passengerId: "PAS-1001",
      flightNumber: "AS-204",
      passengerName: "Captain Alex Miller",
      bookingDate: "2026-08-28T08:00:00.000Z",
      seatNumber: "1B",
      class: "Business",
      ticketPrice: 260,
      paymentStatus: "PAID",
      bookingStatus: "CONFIRMED", // Flight AS-204 booked seat that can be cancelled to test auto-promotion!
    },
    {
      bookingId: "BK-8006",
      passengerId: "PAS-1005",
      flightNumber: "AS-520",
      passengerName: "Elena Rostova",
      bookingDate: "2026-08-29T11:00:00.000Z",
      seatNumber: "2A",
      class: "Business",
      ticketPrice: 690,
      paymentStatus: "PAID",
      bookingStatus: "CONFIRMED",
    },
    {
      bookingId: "BK-8007",
      passengerId: "PAS-1003",
      flightNumber: "AS-410",
      passengerName: "Priya Sharma",
      bookingDate: "2026-08-22T14:00:00.000Z",
      seatNumber: "6A",
      class: "Economy",
      ticketPrice: 65,
      paymentStatus: "REFUNDED",
      bookingStatus: "CANCELLED",
    },
  ];
}

export function getInitialWaitingList() {
  return [
    {
      id: "WL-901",
      passengerId: "PAS-1006", // Marcus Aurelius Vance (VIP - Priority 100)
      passengerName: "Marcus Aurelius Vance",
      flightNumber: "AS-204",
      priority: 100,
      priorityLabel: "VIP Priority",
      requestTime: "2026-08-29T14:20:00.000Z",
      timestamp: new Date("2026-08-29T14:20:00.000Z").getTime(),
      status: "WAITING" as const,
      preferredClass: "Business",
      contactEmail: "marcus.v@heritage.org",
      contactPhone: "+1 555 771 9021",
    },
    {
      id: "WL-902",
      passengerId: "PAS-1002", // Dr. Sarah Chen (Gold - Priority 75)
      passengerName: "Dr. Sarah Chen",
      flightNumber: "AS-204",
      priority: 75,
      priorityLabel: "Gold Frequent Flyer",
      requestTime: "2026-08-29T15:00:00.000Z",
      timestamp: new Date("2026-08-29T15:00:00.000Z").getTime(),
      status: "WAITING" as const,
      preferredClass: "Business",
      contactEmail: "sarah.chen@techglobal.io",
      contactPhone: "+65 9123 4567",
    },
    {
      id: "WL-903",
      passengerId: "PAS-1004", // Rahul Verma (Standard - Priority 25)
      passengerName: "Rahul Verma",
      flightNumber: "AS-204",
      priority: 25,
      priorityLabel: "Economy Standard",
      requestTime: "2026-08-29T16:10:00.000Z",
      timestamp: new Date("2026-08-29T16:10:00.000Z").getTime(),
      status: "WAITING" as const,
      preferredClass: "Business",
      contactEmail: "rahul.v@innovate.co",
      contactPhone: "+91 99887 11223",
    },
  ];
}
